/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTurmasRouteImport } from './routes/app.turmas'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppNotasRouteImport } from './routes/app.notas'
import { Route as AppMasterRouteImport } from './routes/app.master'
import { Route as AppFrequenciaRouteImport } from './routes/app.frequencia'
import { Route as AppEscolaRouteImport } from './routes/app.escola'
import { Route as AppBoletimRouteImport } from './routes/app.boletim'
import { Route as AppAvisosRouteImport } from './routes/app.avisos'
import { Route as AppAdvertenciasRouteImport } from './routes/app.advertencias'
import { Route as AppMasterMigracaoRouteImport } from './routes/app.master.migracao'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTurmasRoute = AppTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasRoute = AppNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterRoute = AppMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AppRoute,
} as any)
const AppFrequenciaRoute = AppFrequenciaRouteImport.update({
  id: '/frequencia',
  path: '/frequencia',
  getParentRoute: () => AppRoute,
} as any)
const AppEscolaRoute = AppEscolaRouteImport.update({
  id: '/escola',
  path: '/escola',
  getParentRoute: () => AppRoute,
} as any)
const AppBoletimRoute = AppBoletimRouteImport.update({
  id: '/boletim',
  path: '/boletim',
  getParentRoute: () => AppRoute,
} as any)
const AppAvisosRoute = AppAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvertenciasRoute = AppAdvertenciasRouteImport.update({
  id: '/advertencias',
  path: '/advertencias',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterMigracaoRoute = AppMasterMigracaoRouteImport.update({
  id: '/migracao',
  path: '/migracao',
  getParentRoute: () => AppMasterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/advertencias': typeof AppAdvertenciasRoute
  '/app/avisos': typeof AppAvisosRoute
  '/app/boletim': typeof AppBoletimRoute
  '/app/escola': typeof AppEscolaRoute
  '/app/frequencia': typeof AppFrequenciaRoute
  '/app/master': typeof AppMasterRouteWithChildren
  '/app/notas': typeof AppNotasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/turmas': typeof AppTurmasRoute
  '/app/': typeof AppIndexRoute
  '/app/master/migracao': typeof AppMasterMigracaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/advertencias': typeof AppAdvertenciasRoute
  '/app/avisos': typeof AppAvisosRoute
  '/app/boletim': typeof AppBoletimRoute
  '/app/escola': typeof AppEscolaRoute
  '/app/frequencia': typeof AppFrequenciaRoute
  '/app/master': typeof AppMasterRouteWithChildren
  '/app/notas': typeof AppNotasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/turmas': typeof AppTurmasRoute
  '/app': typeof AppIndexRoute
  '/app/master/migracao': typeof AppMasterMigracaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/advertencias': typeof AppAdvertenciasRoute
  '/app/avisos': typeof AppAvisosRoute
  '/app/boletim': typeof AppBoletimRoute
  '/app/escola': typeof AppEscolaRoute
  '/app/frequencia': typeof AppFrequenciaRoute
  '/app/master': typeof AppMasterRouteWithChildren
  '/app/notas': typeof AppNotasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/turmas': typeof AppTurmasRoute
  '/app/': typeof AppIndexRoute
  '/app/master/migracao': typeof AppMasterMigracaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/advertencias'
    | '/app/avisos'
    | '/app/boletim'
    | '/app/escola'
    | '/app/frequencia'
    | '/app/master'
    | '/app/notas'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/turmas'
    | '/app/'
    | '/app/master/migracao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/app/advertencias'
    | '/app/avisos'
    | '/app/boletim'
    | '/app/escola'
    | '/app/frequencia'
    | '/app/master'
    | '/app/notas'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/turmas'
    | '/app'
    | '/app/master/migracao'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/advertencias'
    | '/app/avisos'
    | '/app/boletim'
    | '/app/escola'
    | '/app/frequencia'
    | '/app/master'
    | '/app/notas'
    | '/app/perfil'
    | '/app/relatorios'
    | '/app/turmas'
    | '/app/'
    | '/app/master/migracao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/turmas': {
      id: '/app/turmas'
      path: '/turmas'
      fullPath: '/app/turmas'
      preLoaderRoute: typeof AppTurmasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notas': {
      id: '/app/notas'
      path: '/notas'
      fullPath: '/app/notas'
      preLoaderRoute: typeof AppNotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/master': {
      id: '/app/master'
      path: '/master'
      fullPath: '/app/master'
      preLoaderRoute: typeof AppMasterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/frequencia': {
      id: '/app/frequencia'
      path: '/frequencia'
      fullPath: '/app/frequencia'
      preLoaderRoute: typeof AppFrequenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/escola': {
      id: '/app/escola'
      path: '/escola'
      fullPath: '/app/escola'
      preLoaderRoute: typeof AppEscolaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/boletim': {
      id: '/app/boletim'
      path: '/boletim'
      fullPath: '/app/boletim'
      preLoaderRoute: typeof AppBoletimRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/avisos': {
      id: '/app/avisos'
      path: '/avisos'
      fullPath: '/app/avisos'
      preLoaderRoute: typeof AppAvisosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advertencias': {
      id: '/app/advertencias'
      path: '/advertencias'
      fullPath: '/app/advertencias'
      preLoaderRoute: typeof AppAdvertenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/master/migracao': {
      id: '/app/master/migracao'
      path: '/migracao'
      fullPath: '/app/master/migracao'
      preLoaderRoute: typeof AppMasterMigracaoRouteImport
      parentRoute: typeof AppMasterRoute
    }
  }
}

interface AppMasterRouteChildren {
  AppMasterMigracaoRoute: typeof AppMasterMigracaoRoute
}

const AppMasterRouteChildren: AppMasterRouteChildren = {
  AppMasterMigracaoRoute: AppMasterMigracaoRoute,
}

const AppMasterRouteWithChildren = AppMasterRoute._addFileChildren(
  AppMasterRouteChildren,
)

interface AppRouteChildren {
  AppAdvertenciasRoute: typeof AppAdvertenciasRoute
  AppAvisosRoute: typeof AppAvisosRoute
  AppBoletimRoute: typeof AppBoletimRoute
  AppEscolaRoute: typeof AppEscolaRoute
  AppFrequenciaRoute: typeof AppFrequenciaRoute
  AppMasterRoute: typeof AppMasterRouteWithChildren
  AppNotasRoute: typeof AppNotasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTurmasRoute: typeof AppTurmasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvertenciasRoute: AppAdvertenciasRoute,
  AppAvisosRoute: AppAvisosRoute,
  AppBoletimRoute: AppBoletimRoute,
  AppEscolaRoute: AppEscolaRoute,
  AppFrequenciaRoute: AppFrequenciaRoute,
  AppMasterRoute: AppMasterRouteWithChildren,
  AppNotasRoute: AppNotasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTurmasRoute: AppTurmasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
